import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'

export default function Home({content}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
        
        {/*헤더*/}
        <Header/>

        {/**메뉴 */}
        <Nav/>
        
        {/**컨텐츠 */}
    </div>
  )
}
